version: '2.2'
services:
  logstash:
    build: logstash/
    container_name: logstash
    command: -f /logstash.conf
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/logstash.conf
      - ./twitter_template.json:/usr/share/logstash/config/twitter_template.json
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0'
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: 'docker.elastic.co/kibana/kibana-oss:7.0.0'
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"

volumes:
  esdata1:
    driver: local